### ISSUE TITLE
Supporting discrete action space?

### ISSUE THREAD

**Issue by Steven-xzr** [ToruOwO/minimal-stable-PPO#2]
Hi @ToruOwO , the codes of this repo are very easy to read and at the same time performant enough, which I appreciate so much. However, it seems that your implementation only supports continuous action space. If it is the case, will you consider to add support for discrete action space in the future?

The reason why I'm interested in discrete action space is that I'm now working with a customized RL environment that leverages Isaac Gym to accelerate the physics simulation but has a customized **discrete** action space. Unfortunately, I find that **Isaac Gym acceleration + discrete action space** is a demand seldom considered by mainstream RL frameworks on the market.

I would be very grateful if you could help implement the discrete action space version of PPO, or just provide any potentially helpful suggestions. Looking forward to your reply!

**Comment by ToruOwO** [comment]
Thanks for the interest! This is a good suggestion, though unfortunately I have not yet found a time to work on this.

One good reference on how to support discrete action space is [this](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/blob/master/a2c_ppo_acktr/model.py) file (check out the Categorical action space implementation). Hope it helps!
