### ISSUE TITLE
A Small Typo in the Model Initialization Code?

### ISSUE THREAD

**Issue by ColinQiyangLi** [ToruOwO/minimal-stable-PPO#3]
In `ppo/models.py`  [L64](https://github.com/ToruOwO/minimal-stable-PPO/blob/ffe699a56f6597cea5e833c9a118f7a624e58590/ppo/models.py#L64), should it be `torch.nn.init.orthogonal_(self.mu.weight, gain=0.01)`? Currently, the code seems to be initializing the value final layer twice.

**Comment by ToruOwO** [comment]
Thanks for pointing out! Just fixed :)
